### ISSUE TITLE
Methods return nil

### ISSUE THREAD

**Issue by aandis** [osiro/enceladus#3]
Any call I make returns nill.

    Enceladus.connect("<my_key>")
    collection = Enceladus::Movie.find("tt0137523")
    puts collection #prints nill

Pretty sure, my api key is correct. I can make the calls directly to the `tmdb` api with the key just fine.

**Comment by aandis** [comment]
Turns out the api

**Comment by osiro** [comment]
Thanks for letting us know @aandis, will check what the api returns to us in case it's incorrect, raising an exception is actually better than just return nil.

**Comment by aandis** [comment]
Hmm. Yeah. Good idea. :)
